// AUTO-GENERATED by scripts/process-library.mjs — do not edit by hand.
export type LibraryCategory = 'interiors' | 'materials' | 'exteriors' | 'lifestyle' | 'process' | 'backgrounds'

export interface LibraryImage {
  slug: string
  category: LibraryCategory
  src: string
  w: number
  h: number
  aspectRatio: number
  blurDataURL: string
  alt: string
}

export const imageLibrary: LibraryImage[] = [
  {
    "slug": "interior-living-warm-01",
    "category": "interiors",
    "src": "/library/interiors/interior-living-warm-01.jpg",
    "w": 1920,
    "h": 1364,
    "aspectRatio": 1.408,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAsABABoJYwCw7Dw2C+/tRcAAOJ8w8VN9X6XLS+Js66QvsMnFvvDWglPOjxR8SCMk4KGD3t98huTvmRS0fzhloQAAA==",
    "alt": "Warm living room with natural light"
  },
  {
    "slug": "interior-living-warm-02",
    "category": "interiors",
    "src": "/library/interiors/interior-living-warm-02.jpg",
    "w": 1920,
    "h": 2880,
    "aspectRatio": 0.667,
    "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABQBACdASoQABgAPxFysFAsJqSisAgBgCIJQBOgBDfPD3HcLgVxyUdtDw2wAP5laBKTFReocsiXwR40OUsc+uMDxXjMDjJuVPJmWnKy7chQwgQ01oCvZRDMhm/YNd+pPmy9r9GjF1f5Lz9n3aU2YWh8gBOdeAAA",
    "alt": "Modern living space with sculptural lighting"
  },
  {
    "slug": "interior-living-warm-03",
    "category": "interiors",
    "src": "/library/interiors/interior-living-warm-03.jpg",
    "w": 1920,
    "h": 2560,
    "aspectRatio": 0.75,
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQBACdASoQABUAPxFysFAsJqSisAgBgCIJZQC07AgBS5Da55eL0vE4AAD9+f8cXoJ7dIAP2mL5eAECzzgMOMkam9rhFjsHX77Jawf1b4w+7nmQN/UYG8st8R5Vs58n/ddpVPvRldnHG5Zx+WLXZqNAAAA=",
    "alt": "Cozy interior with layered textiles"
  },
  {
    "slug": "interior-living-luxury-01",
    "category": "interiors",
    "src": "/library/interiors/interior-living-luxury-01.jpg",
    "w": 1920,
    "h": 1006,
    "aspectRatio": 1.908,
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAgABABoJYwCdADxA1Y/2yAAy0sDh1McGCg6Bo52AIIvXNCqhYoMeEKmIOB1d7krBjPtz53jWl+QgAA=",
    "alt": "Luxury interior with custom millwork"
  },
  {
    "slug": "interior-bedroom-warm-01",
    "category": "interiors",
    "src": "/library/interiors/interior-bedroom-warm-01.jpg",
    "w": 1920,
    "h": 1280,
    "aspectRatio": 1.5,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAsABABoJZgCdAEPCDi6RxIAAP5b3BwJTTnkjSj57KnDiNxdNPn00p1jGNQZnSmBc+qHZvlFSj1ZCOZJFoIK08je3oBqgAA=",
    "alt": "Bedroom with warm timber finishes"
  },
  {
    "slug": "interior-bedroom-warm-02",
    "category": "interiors",
    "src": "/library/interiors/interior-bedroom-warm-02.jpg",
    "w": 1920,
    "h": 1280,
    "aspectRatio": 1.5,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAsABABoJYwCdADHdRSw+9AAAP7vYdmd7rRX/255JiIsks2XOH47iOHJx8IGD90G2xU8vC766Ny1bvg7PN+3wZLTotOpeSdRYvL8gVDQAA==",
    "alt": "Bedroom with sculpted headboard"
  },
  {
    "slug": "interior-kitchen-modern-01",
    "category": "interiors",
    "src": "/library/interiors/interior-kitchen-modern-01.jpg",
    "w": 1920,
    "h": 1280,
    "aspectRatio": 1.5,
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABwAgCdASoQAAsABABoJbACdB2gDZMrIFXxTPQAAP2UUTlOq2Zm7TrQtQi31ShdlB1QTUv1l0LR4BOlS5d3Pz1HogTJNfCdL+OXHcqXAIBKo66KYoaab64jGmbD5/TvxToj4zjTKWwAAA==",
    "alt": "Modern kitchen with stone island"
  },
  {
    "slug": "interior-kitchen-modern-02",
    "category": "interiors",
    "src": "/library/interiors/interior-kitchen-modern-02.jpg",
    "w": 1920,
    "h": 2400,
    "aspectRatio": 0.8,
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQAwCdASoQABQAPxFysFAsJqSisAgBgCIJYgAAMgkQwB9DlNgCh1AAzA2y90wo7QVXKplKVcRNJUZNjfC1Nv1vNvh8PzUyt6RP3OnudBGTjZ5wiSCrWZQpDodYQfVlr2KNOO0h6aCu14AA",
    "alt": "Kitchen with hand-finished cabinetry"
  },
  {
    "slug": "interior-dining-warm-01",
    "category": "interiors",
    "src": "/library/interiors/interior-dining-warm-01.jpg",
    "w": 1920,
    "h": 1280,
    "aspectRatio": 1.5,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAsABABoJZQCw7DQI/IAAPuZT9J0v4e8RnBvNaZjeEZkhDoiKk/Kg03Vqqbay88FWp0yqumM9xHjb9ZIaqUPjAAAAA==",
    "alt": "Dining room with sculptural pendant"
  },
  {
    "slug": "interior-bath-stone-01",
    "category": "interiors",
    "src": "/library/interiors/interior-bath-stone-01.jpg",
    "w": 1920,
    "h": 1004,
    "aspectRatio": 1.912,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAgABABoJYwC7ACZd6CSwAD+cYQ2izArJzD1cVFMaDoIAfDELkV0mHmlDodiNVURG/WXZ3sIzSAA",
    "alt": "Stone bathroom with natural light"
  },
  {
    "slug": "interior-detail-warm-01",
    "category": "interiors",
    "src": "/library/interiors/interior-detail-warm-01.jpg",
    "w": 1920,
    "h": 2560,
    "aspectRatio": 0.75,
    "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABwAwCdASoQABUAPxFwsFAsJiSisAgBgCIJZAC7AYxETAeNQyAA1oUcWFogX8TPh9hbPZrlYE0qNI+mYX9gafRTXmnIOQtnbIkUOKMMEX0KGsB+ttw9OkPlYDSYuQI+ecJf4FTqTika3M1iGtt9naE6ndxLgAAA",
    "alt": "Interior detail with warm wood"
  },
  {
    "slug": "interior-detail-warm-02",
    "category": "interiors",
    "src": "/library/interiors/interior-detail-warm-02.jpg",
    "w": 1920,
    "h": 2450,
    "aspectRatio": 0.784,
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADwAwCdASoQABQAPxFwsFAsJiSisAgBgCIJaACdACG3u2I57dGFLD0AAPjDHVWvoWfAMPm6Ju9mUuQCQN4OgE8HGU1+u5aNGyf2wuqjpcvuuTeA1UpgjmrNO1pKGxXKG61ydnJhQRcDiSGJLvEx8Nsghi7BgbMFw3dmV4AA",
    "alt": "Architectural interior corner"
  },
  {
    "slug": "interior-detail-warm-03",
    "category": "interiors",
    "src": "/library/interiors/interior-detail-warm-03.jpg",
    "w": 1920,
    "h": 1280,
    "aspectRatio": 1.5,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAsABABoJbACdADxNG8TIN0MAAD+eSEY+pcqbaOV7v0JibFXWYLKxU+QkgW3ohQVfMee+9PEcD8/s09vnd7b7Q0tR7ppbl96ewv+AAA=",
    "alt": "Interior with curated objects"
  },
  {
    "slug": "interior-luxury-01",
    "category": "interiors",
    "src": "/library/interiors/interior-luxury-01.jpg",
    "w": 1920,
    "h": 971,
    "aspectRatio": 1.978,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAQCdASoQAAgABABoJQBOgMV9a3CgAMkztBR/Nq8nS4VGVu2W4qb7J7bDe/0d7l9I7JB3S7bRBo4FhNlXSTv5rw/1S3PQqpUxl9kkMPMwAA==",
    "alt": "Luxury residential interior"
  },
  {
    "slug": "interior-luxury-02",
    "category": "interiors",
    "src": "/library/interiors/interior-luxury-02.jpg",
    "w": 1920,
    "h": 706,
    "aspectRatio": 2.72,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAYABABoJQBOgCHeKS8xQAD+7Q9SMQNVU5gENbkcHGFH5pAK6UZygX/YETGSGdxn/dkn/iZ8JMgA",
    "alt": "High-end residential space"
  },
  {
    "slug": "interior-luxury-03",
    "category": "interiors",
    "src": "/library/interiors/interior-luxury-03.jpg",
    "w": 1920,
    "h": 1280,
    "aspectRatio": 1.5,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoQAAsABABoJbACdAEPdXY71mBAAP6dUXLHqZLMi2Rh0fU/1sP+8BhHvun7CEUF86fzI7gA",
    "alt": "Refined contemporary interior"
  },
  {
    "slug": "interior-luxury-04",
    "category": "interiors",
    "src": "/library/interiors/interior-luxury-04.jpg",
    "w": 1920,
    "h": 1280,
    "aspectRatio": 1.5,
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAsABABoJYwCdAEPDIv4twAA/uGL70/a2nPwxpkrWixup8eZtxgeByp063ACLxRJf9K0KNvzsY3gAAA=",
    "alt": "Designer interior composition"
  },
  {
    "slug": "interior-luxury-05",
    "category": "interiors",
    "src": "/library/interiors/interior-luxury-05.jpg",
    "w": 1920,
    "h": 1080,
    "aspectRatio": 1.778,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAQCdASoQAAkABABoJQBOgBVT9ZQAAP3wNwhc/wl8PvJLhtKqaitgV06llFo2NpgXIN1p+LPilCbs44H92/SOWNNxtVn31s1PFzPa8gA=",
    "alt": "Premium residential detail"
  },
  {
    "slug": "interior-luxury-06",
    "category": "interiors",
    "src": "/library/interiors/interior-luxury-06.jpg",
    "w": 1920,
    "h": 1080,
    "aspectRatio": 1.778,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAQCdASoQAAkABABoJQBOgBwuvjQA4hCXqT8caNeX9vH41OTNqkOynxzoSuX9aQ/vs17Mz4UMAAAA",
    "alt": "Editorial interior shot"
  },
  {
    "slug": "interior-modern-01",
    "category": "interiors",
    "src": "/library/interiors/interior-modern-01.jpg",
    "w": 1920,
    "h": 1282,
    "aspectRatio": 1.498,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoQAAsABABoJaQAAvp56Jr9FyKwAAD92++Nr1iBhWhWFAF6QsLkTC1hvll54EDGHG+u/8pTZk1vJ/vDVAltrH71lXWJ4dEcHTIrYAAA",
    "alt": "Modern interior with curated decor"
  },
  {
    "slug": "interior-modern-02",
    "category": "interiors",
    "src": "/library/interiors/interior-modern-02.jpg",
    "w": 1920,
    "h": 1281,
    "aspectRatio": 1.498,
    "blurDataURL": "data:image/webp;base64,UklGRiwAAABXRUJQVlA4ICAAAABQAQCdASoQAAsABABoJZwABAAAAP7uN7r+QZhD1uKAAA==",
    "alt": "Contemporary residential interior"
  },
  {
    "slug": "interior-modern-03",
    "category": "interiors",
    "src": "/library/interiors/interior-modern-03.jpg",
    "w": 1920,
    "h": 1281,
    "aspectRatio": 1.498,
    "blurDataURL": "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAABQAQCdASoQAAsABABoJZwABAAAAP7vrgh24oAA",
    "alt": "Modern home interior view"
  },
  {
    "slug": "interior-modern-04",
    "category": "interiors",
    "src": "/library/interiors/interior-modern-04.jpg",
    "w": 1920,
    "h": 1920,
    "aspectRatio": 1,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQABAABABoJZwAAfbW6/927AAA95/pDFyBI8uIxu4tkmaUOAfcWMK6FnTrdx1LN3lFYpTJHd+sCJ4s8rLo8hMYBgwIAA==",
    "alt": "Open-plan modern interior"
  },
  {
    "slug": "exterior-modern-01",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-modern-01.jpg",
    "w": 1920,
    "h": 2718,
    "aspectRatio": 0.707,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABwAwCdASoQABcAPxF4tFGsJyUisAgBgCIJZQAAexgg1ZBtr8AA/uvTpPD/gRDrwuds3OlituHobChSJy84AMN2omBCZVWeTnSWm9lIoY+6tckiUAAAAA==",
    "alt": "Contemporary architecture facade"
  },
  {
    "slug": "exterior-modern-02",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-modern-02.jpg",
    "w": 1920,
    "h": 1280,
    "aspectRatio": 1.5,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAsABABoJQBOgBxu0q7ioucAAP6YVag2k6RaElbIdMhkijcGJcGDEmMUc9vTZZY1GWHajfA3fjkAVFJC/HI+xJ1ESkcRVOJxVNzsopeAAA==",
    "alt": "Modern building exterior"
  },
  {
    "slug": "exterior-modern-night-01",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-modern-night-01.jpg",
    "w": 1920,
    "h": 2874,
    "aspectRatio": 0.668,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwBACdASoQABgAPxFwsFAsJiSisAgBgCIJZQC2yBuHuZZ8jZWAHViGh4AA/t2dDLTq84C9PiBcfDdljzximOyLiTcLxJhEC2isYHSzEhLSR71fMBeFRo2mI21n2ft6AAA=",
    "alt": "Architecture at twilight"
  },
  {
    "slug": "exterior-modular-01",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-modular-01.jpg",
    "w": 1920,
    "h": 1291,
    "aspectRatio": 1.488,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAsABABoJYgC7AD2H7SwAIAA/lto/we+RigyP6JlabNrughcoYIPRsr82TAQeqHqulOHTfvFMJ09yjflJnNeOptyEkAA",
    "alt": "Modular architecture exterior"
  },
  {
    "slug": "exterior-modular-02",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-modular-02.jpg",
    "w": 1920,
    "h": 1080,
    "aspectRatio": 1.778,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAAkABABoJYgCsAD1UH7QAM3ZEO0i3Rfoglf6AZe1oSKIGpvdyqgKfVrtAEjaOizkHC6QGUBy2ThF+wAAAA==",
    "alt": "Prefab architectural form"
  },
  {
    "slug": "exterior-render-01",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-render-01.jpg",
    "w": 1920,
    "h": 1080,
    "aspectRatio": 1.778,
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkABABoJYgAAueNW8OIAAD+83aOuX5rxKGt4KFHEeH4ko1TLfDGTebFsXq1Mi/xKKKSGp/9JsgAAAA=",
    "alt": "Architectural visualization"
  },
  {
    "slug": "exterior-modern-03",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-modern-03.jpg",
    "w": 1920,
    "h": 1280,
    "aspectRatio": 1.5,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAwAgCdASoQAAsABABoJZQCdAEeb/7CF94AAAD8GL1+n0de+xzbaSk5haNilMyZM67e1W8lNntYPWxfzOWNfR1slfsZcf//J1AAAA==",
    "alt": "Sculptural building exterior"
  },
  {
    "slug": "exterior-modern-04",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-modern-04.jpg",
    "w": 1920,
    "h": 2400,
    "aspectRatio": 0.8,
    "blurDataURL": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAQBACdASoQABQAPxFysFAsJqSisAgBgCIJaQAIEAKurNg8YAjxS81kAAD+7qHyp+0j4/w4ji34NpcZ4BxykOubakyND8T6G+mUOLgsbqUlhe/Jnt0fN/MUhCN/t99p0caTALceg7xAFS484NmDKgDwndF0K9sPi4d8ItEiGrGhnQnAAAA=",
    "alt": "Geometric architectural form"
  },
  {
    "slug": "exterior-modern-05",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-modern-05.jpg",
    "w": 1920,
    "h": 1080,
    "aspectRatio": 1.778,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkABABoJQBOgCP6dhvCikAA/ZADrHaiflEpafJZD07OStUHWkTfWdV4+LwaEYN78FIy0Juc0z7x68j1Ubb3dwAAAA==",
    "alt": "Contemporary architectural detail"
  },
  {
    "slug": "exterior-detail-01",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-detail-01.jpg",
    "w": 1920,
    "h": 1200,
    "aspectRatio": 1.6,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAoABABoJQBOgBmjpaqml3QAAP2UkeBnl5NbNASZZ99E+lfCjXzae53+bOkfXtpXgQO/S595i2GcyOtaewWfze8pKQAA",
    "alt": "Architectural facade detail"
  },
  {
    "slug": "exterior-detail-02",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-detail-02.jpg",
    "w": 1920,
    "h": 1200,
    "aspectRatio": 1.6,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAwAgCdASoQAAoABABoJZQC7AEWYUxkJkyhMAD81qh87DMZE/t+lD0B8vz+ef+nDPK4obWGRAm7j1JylY10JoTBmAqkaAAA",
    "alt": "Architectural composition"
  },
  {
    "slug": "exterior-modern-06",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-modern-06.jpg",
    "w": 1920,
    "h": 1371,
    "aspectRatio": 1.401,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAsABABoJYgCdACqHaB/CUAA/mTa4Y8x5tXp9fkKbFfpo1YHytaE4p/6GdYs0GYN1W3262OiIhkIYUj/rc2GEwEuUU95AAA=",
    "alt": "Modern building study"
  },
  {
    "slug": "exterior-modern-07",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-modern-07.jpg",
    "w": 1920,
    "h": 1371,
    "aspectRatio": 1.401,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAsABABoJYgCdAEe1GbtMjJ0AADhkX+spVfISLXj16UkKc/Hj6FfER97gcLoEmEY7Qp2z9au7vKtn4feq1zEbJoDdMKlDy5chxTtr4AmPwAA",
    "alt": "Architectural form study"
  },
  {
    "slug": "exterior-modern-08",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-modern-08.jpg",
    "w": 1920,
    "h": 1371,
    "aspectRatio": 1.401,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAAsABABoJZACdAEe+ab19UJgAAD+SeGZ+t5P/0L60+AfnJ5DOIkMAGhxAOqBdvH2RUd0ERTxIiAVLbK9EXJVOcrd4+5Fj2ZoEutptIi7D4E3XOEAAA==",
    "alt": "Building geometry study"
  },
  {
    "slug": "exterior-modern-09",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-modern-09.jpg",
    "w": 1920,
    "h": 1310,
    "aspectRatio": 1.466,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAsABABoJQBOgB7HZwYTkEAAAOAGYEk0hiOCutQ9COG2k3CkoELq7fdDFlGXI8AHUQFPacTzmpwUQrAUtilxuApwHlc/q2hUJIzOxpyGyKiTtQAAAA==",
    "alt": "Contemporary residential exterior"
  },
  {
    "slug": "exterior-modern-10",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-modern-10.jpg",
    "w": 1920,
    "h": 1601,
    "aspectRatio": 1.199,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAA0ABABoJQBOgB5MnW7AAP5mvyMyR+aGCqp462PWdM8XunaICDB8Oh9SMqJzBDy51hRDQcQ50UMSNMMWW4c2qMmCFd4+md9O/IAA",
    "alt": "Architectural composition"
  },
  {
    "slug": "exterior-detail-03",
    "category": "exteriors",
    "src": "/library/exteriors/exterior-detail-03.jpg",
    "w": 1920,
    "h": 1078,
    "aspectRatio": 1.78,
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoQAAkABABoJZwAAtTBIxPAAPzSrjoCDz3eiLHzDpfOcf1pqEP5qy0UOpxbAAAA",
    "alt": "Architectural surface detail"
  },
  {
    "slug": "material-texture-01",
    "category": "materials",
    "src": "/library/materials/material-texture-01.jpg",
    "w": 1920,
    "h": 1272,
    "aspectRatio": 1.51,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAsABABoJYwCdAEGIDoB4AD+6GCBRz1pRX937LZsQkptGpEzHtclIYKp5Gjci3QWwgzQXsebNQbUaPr011oEl+31tVZXQ/0mgAAA",
    "alt": "Material texture study"
  },
  {
    "slug": "material-texture-02",
    "category": "materials",
    "src": "/library/materials/material-texture-02.jpg",
    "w": 1920,
    "h": 1280,
    "aspectRatio": 1.5,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABwAgCdASoQAAsABABoJZQCdAae/mly9OwlbmIAAP67aPDfSOd4WSY/ezxx82nsux233C670mMxq+otrJ9FPE7EPRK68zUbSfgybzho8a6VdXbszUve0HT6SjuRhM8AAAA=",
    "alt": "Surface composition"
  },
  {
    "slug": "material-texture-03",
    "category": "materials",
    "src": "/library/materials/material-texture-03.jpg",
    "w": 1920,
    "h": 2400,
    "aspectRatio": 0.8,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADQAwCdASoQABQAPxFysVAsJqSisAgBgCIJQBOmUABptcLpzPxhQ7AA/sAdVx+6tmi2uNC1kuQswQxdHCcu5xniRYtW+1JnX1ow0Z/GEUJaO1RdAE6N7uZt8b95smcMxJn2OuawOMfkqCb/b9QYLcwA",
    "alt": "Material study"
  },
  {
    "slug": "lifestyle-studio-01",
    "category": "lifestyle",
    "src": "/library/lifestyle/lifestyle-studio-01.jpg",
    "w": 1920,
    "h": 1440,
    "aspectRatio": 1.334,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAwAgCdASoQAAwABABoJZQCw7EPEGmUdLNr4AD+50LFjq66p/nMHK9frlNPe0SgNnfteN01ekZy5AVoiMgt3CFs5fyQAA==",
    "alt": "Design studio workspace"
  },
  {
    "slug": "lifestyle-studio-02",
    "category": "lifestyle",
    "src": "/library/lifestyle/lifestyle-studio-02.jpg",
    "w": 1920,
    "h": 1536,
    "aspectRatio": 1.25,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoQAA0ABABoJZwAAgfQwt6AANvkCrt8X/qPl5QsEOYQJloGdUvjGnmPdhiz/jp/346yypi9UZT04QAA",
    "alt": "Workspace details"
  },
  {
    "slug": "lifestyle-studio-03",
    "category": "lifestyle",
    "src": "/library/lifestyle/lifestyle-studio-03.jpg",
    "w": 1920,
    "h": 2400,
    "aspectRatio": 0.8,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACwAwCdASoQABQAPxFwsFAsJiSisAgBgCIJQBUehDmJsPflKnKDLAD+evLNDsBe2l2L/w5vcILFiXLLrSH0b5MlW1LfJx0XJatmN+wLMX2Ow1W3TPdCIb2/3DAB7NdWC4BpDJikzv/mcZ4cluNt6QAA",
    "alt": "Studio environment"
  },
  {
    "slug": "lifestyle-studio-04",
    "category": "lifestyle",
    "src": "/library/lifestyle/lifestyle-studio-04.jpg",
    "w": 1920,
    "h": 1080,
    "aspectRatio": 1.778,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkABABoJZwAAq9c+LvRs/AA+TI0yNbLsD4UjVYpS7m85uG2BOFJ2l2bcXXUxl5zBV+PqMUhezut3fCAAA==",
    "alt": "Creative workspace"
  },
  {
    "slug": "lifestyle-desk-01",
    "category": "lifestyle",
    "src": "/library/lifestyle/lifestyle-desk-01.jpg",
    "w": 1920,
    "h": 1080,
    "aspectRatio": 1.778,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAkABABoJQBOgMWMxbb+0QAA/oey4T1r8dlWy0Xi09QfoGIRMWnO68/R0SL2Mt+domptO8JpfYa4Ora8tWCFeLOEbFQCXw0sFjStRxgAAA==",
    "alt": "Designer desk with samples"
  }
]

export const byCategory: Record<LibraryCategory, LibraryImage[]> = {
  interiors:   imageLibrary.filter(i => i.category === 'interiors'),
  materials:   imageLibrary.filter(i => i.category === 'materials'),
  exteriors:   imageLibrary.filter(i => i.category === 'exteriors'),
  lifestyle:   imageLibrary.filter(i => i.category === 'lifestyle'),
  process:     imageLibrary.filter(i => i.category === 'process'),
  backgrounds: imageLibrary.filter(i => i.category === 'backgrounds'),
}

export function pickBySlug(slug: string): LibraryImage | undefined {
  return imageLibrary.find(i => i.slug === slug)
}
